spring.application.name=gestion
#  Puerto del servidor (opcional, 8080 es el por defecto)
server.port=8081

# Definimos la dirección del microservicio interno
ms.alertas.url=http://localhost:8082

# Cambia 'TU_TENANT_ID' por el ID de tu directorio en Azure
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/d7e7e206-ec2c-460a-a160-6f1cdd447720/v2.0